### ISSUE TITLE
distOrth_interactive.py documentation

### ISSUE THREAD

**Issue by AlexdeMendoza** [ballesterus/UPhO#3]
Hi, I really like your package, I am trying it and I am geting some promising results. However, I would really appreciate some documentation on distOrth_interactive.py (or distOrth.py), as I cannot manage to get it to work. What kind of data do you need to generate a OG_summary file? What kind of species tree is expecting (distances, supports, or just a simple cladogram)?
Moreover, I'd like to know what is the diference between orthogroups that have a _1 (such as OG0000036_0  and OG0000036_1), I see that in some cases all genes overlap between both groups but one, and some times all the genes are completely different. 

Thanks in advance for your answer.

Alex

**Comment by ballesterus** [comment]
Alex, 
Thanks for your interest. I have just uploaded a  more complete  (or so I think) manual (Documentation.pdf).
I hope that how to deal with distOrth and distOrth_interactive is better explained there. I made recent modifications to distOrth so that the orthogroups text file (or similarly formatted) can be parsed. 
As for the tree, any Newick formatted file should be OK for proper parsing, regardless of branch lengths,  support, rooting, etc.
OG0000036_0 and OG00000036_1  are both ortho-groups derived from the tree OG0000036. One of the things that can be done; is opening the gene family tree and the ortho-branches in FigTree, (2) Navigate to the each orthologous tree and color the tip labels. (3), navigate back to the gene family tree and voila!, you should see where these branches come from and how the orthology is evaluated.  The cases were they overlap are caused by ambiguity in the orthology assessment (possible due to sampling effects) and the sequences in the intersection could belong to one or the other orthogroup.
 An option in distOrth_interactive, will allow you to solve these redundancies arbitrarily by selecting the largest orthogroup.  However, these instances would require additional evidence to be properly resolved.
I apologize for the lengthy response. And let me know if you have more questions.

Best

Chuy
